// Configuration for Schoolmate-Ai Bot
module.exports = {
  // Replace with your Telegram Bot Token from BotFather
  TELEGRAM_TOKEN: process.env.TELEGRAM_TOKEN || 'YOUR_BOT_TOKEN_HERE',

  punishment: {
    softThresholdHours: 24,
    hardThresholdDays: 3,
    xpPenalty: 50,
    freezeItemCost: 100,
    riskThresholdHours: 18,
    checkIntervalHours: 6,
  },

  exams: {
    defaultTimezone: 'Europe/Kyiv',
    checkIntervalMinutes: 1,
    reminderWindowMinutes: 10,
    reminders: [
      { field: 'notified2d', offsetMs: 2 * 24 * 60 * 60 * 1000, messageKey: 'examReminder2d' },
      { field: 'notified1d', offsetMs: 24 * 60 * 60 * 1000, messageKey: 'examReminder1d' },
      { field: 'notified2h', offsetMs: 2 * 60 * 60 * 1000, messageKey: 'examReminder2h' },
    ],
  },

  quiz: {
    xpPerCorrect: 5,
    allowedCounts: [3, 5, 7, 10],
    difficulties: ['easy', 'medium', 'hard'],
  },

  premium: {
    // Comma-separated IDs can also be set via PREMIUM_USER_IDS in .env
    maxPhotoBytes: 8 * 1024 * 1024,
    maxVoiceBytes: 4 * 1024 * 1024,
  },

  duel: {
    questionCount: 5,
    answerTimeoutMs: 20000,
    matchmakingTimeoutMs: 60000,
    inviteTtlMs: 15 * 60 * 1000,
    basePoints: 100,
    maxSpeedBonus: 50,
    aiCorrectChance: 0.7,
    xpWin: 25,
    xpDraw: 10,
    xpLoss: 5,
    rating: { win: 15, loss: -5, draw: 5, min: 0 },
  },

  // Bot messages
  messages: {
    start: 'Привіт 👋 Ласкаво просимо до Schoolmate AI!\n\nЯ допоможу тобі з навчанням. Вибери, що тебе цікавить:',
    explainTopic: 'Яку тему ти хочеш розібрати? Напиши назву теми або номер параграфа.',
    createTest: '🧠 <b>Створення тесту</b>\n\nAI згенерує тест із варіантами відповідей за твоєю темою або матеріалом.',
    quizAskTopic: '🧠 <b>Створення тесту</b>\n\nНапиши <b>тему</b> або надішли <b>навчальний матеріал</b> (текст чи .txt/.md файл).\n\nПриклад: <i>Фотосинтез</i> або встав текст параграфа.\n\n<i>Скасувати: «⬅️ Повернутися в меню»</i>',
    quizAskCount: '📊 Скільки запитань згенерувати?\n\nОбери кнопку або напиши число: <b>3</b>, <b>5</b>, <b>7</b> або <b>10</b>.',
    quizAskDifficulty: '🎯 Обери рівень складності:\n\n🟢 Легкий · 🟡 Середній · 🔴 Складний\n\nАбо напиши: <i>легкий</i> / <i>середній</i> / <i>складний</i>.',
    quizGenerating: '⏳ Генерую тест за допомогою AI... Це може зайняти кілька секунд.',
    quizReady: '✅ Тест готовий!\nЗапитань: <b>{count}</b>\nСкладність: <b>{difficulty}</b>\n\nПочинаємо 👇',
    quizGenerateError: '❌ Не вдалося згенерувати тест. Спробуй іншу тему або матеріал пізніше.',
    quizTopicTooShort: 'Тема або матеріал занадто короткі. Напиши мінімум 2 символи.',
    quizUnsupportedFile: '📄 Поки підтримуються текстові файли (<b>.txt</b>, <b>.md</b>, <b>.csv</b>).\nАбо просто встав текст повідомленням.',
    quizFileTooLarge: '📄 Файл занадто великий. Надішли файл до 200 КБ або встав текст.',
    quizReadingFile: '📄 Читаю файл...',
    quizFileReadError: '❌ Не вдалося прочитати файл. Спробуй інший файл або встав текст.',
    quizWaitGenerating: '⏳ Зачекай, тест ще генерується...',
    quizUseButtons: '☝️ Обери варіант відповіді кнопками під запитанням.',
    quizAnswerCorrect: '✅ <b>Правильно!</b>',
    quizAnswerWrong: '❌ Неправильно. Правильна відповідь: <b>{answer}</b>',
    quizFinished: '🏁 <b>Тест завершено!</b>',
    quizStopped: '⏹ <b>Тест зупинено</b>',
    quizCancelled: 'Створення тесту скасовано.',
    premiumRequired: '⭐ <b>Premium-функція</b>\n\nАналіз фото та голосових повідомлень тимчасово недоступний. Спробуй пізніше.\nТвій ID: натисни /premium',
    premiumInfo: '⭐ <b>SchoolMate Premium</b>\n\nСтатус: <b>{status}</b>\nТвій Telegram ID: <code>{userId}</code>\n\nPremium доступний <b>для всіх</b> і відкриває:\n• 🖼️ розбір фото (задачі, графіки, тексти підручника, пошук помилок)\n• 🎤 відповіді на голосові повідомлення\n• 🔊 озвучку відповідей для іноземних мов (опційно)',
    premiumPhotoAnalyzing: '🖼️ Аналізую зображення через Gemini Vision...',
    premiumVoiceAnalyzing: '🎤 Розпізнаю голосове повідомлення...',
    premiumMediaError: '❌ Не вдалося обробити медіафайл. Спробуй чіткіше фото або коротший голосовий запис пізніше.',
    premiumMediaTooLarge: '❌ Файл занадто великий для обробки. Надішли менше фото або коротше голосове.',
    duelSearching: '⚔️ <b>Дуель знань</b>\n\n🔍 Шукаю суперника в черзі…\n\nЗачекай або скасуй пошук.',
    duelMenu: '⚔️ <b>Дуель знань</b>\n\nТвій Telegram ID: <code>{userId}</code>\n(скинь його другу, щоб він міг запросити тебе)\n\nОбери спосіб гри:',
    duelAskFriendId: '👥 <b>Запросити друга</b>\n\nВведи <b>Telegram ID</b> друга (число).\nДруг може дізнатись свій ID у меню дуелі або через /premium / /duel.\n\n<i>Скасувати: «⬅️ Повернутися в меню»</i>',
    duelAskJoinCode: '🔑 <b>Приєднатися за кодом</b>\n\nВведи код запрошення від друга (наприклад <code>A1B2C3</code>).',
    duelFriendIdInvalid: '❌ Невірний ID. Введи лише цифри Telegram ID (5–15 символів).',
    duelFriendIdSelf: '❌ Не можна грати сам із собою 😄',
    duelFriendBusy: '⏳ Цей гравець зараз уже в дуелі. Спробуй пізніше.',
    duelFriendNotRegistered: 'ℹ️ Друг ще не запускав бота або не завершив реєстрацію.\nНадішли йому <b>код запрошення</b> — він зможе приєднатися через «Приєднатися за кодом».',
    duelInviteCreated: '✅ Запрошення створено!\n\nДруг ID: <code>{friendId}</code>\nКод: <code>{code}</code>\n\nДруг може натиснути «Прийняти» у повідомленні або ввести код у меню дуелі.\nКод діє 15 хвилин.',
    duelInviteReceived: '⚔️ <b>{name}</b> (ID <code>{userId}</code>) запрошує тебе на дуель знань!\n\nКод: <code>{code}</code>\nПрийми запрошення або відхили.',
    duelInviteNotifyFailed: '⚠️ Не вдалося надіслати повідомлення другу напряму. Передай йому код запрошення вручну.',
    duelInviteNotFound: '❌ Запрошення не знайдено або вже неактивне.',
    duelInviteExpired: '⏱️ Термін запрошення минув. Попроси друга створити нове.',
    duelInviteWrongUser: '❌ Це запрошення адресоване іншому гравцю.',
    duelInviteDeclinedSelf: 'Ти відхилив(ла) запрошення на дуель.',
    duelInviteDeclinedHost: '😔 {name} відхилив(ла) твоє запрошення на дуель.',
    duelInviteCancelled: '❌ Запрошення скасовано.',
    duelSearchingHint: '🔍 Йде пошук суперника. Натисни «Скасувати пошук» або зачекай.',
    duelInvitePendingHint: '⏳ Чекаємо, поки друг прийме запрошення. Можеш скасувати його кнопкою під повідомленням.',
    duelNoOpponent: '⏱️ Суперника не знайдено понад 1 хвилину.\n\nМожеш зіграти з <b>ШІ</b> або скасувати пошук.',
    duelSearchCancelled: '❌ Пошук суперника скасовано.',
    duelNotSearching: 'Ти зараз не в черзі пошуку.',
    duelMatched: '⚔️ <b>Суперника знайдено!</b>\nСуперник: <b>{opponent}</b>\n\nГотуємо 5 запитань…',
    duelGenerating: '🧠 Генерую запитання для дуелі…',
    duelAnswerCorrect: '✅ Правильно! <b>+{points}</b> балів',
    duelAnswerWrong: '❌ Неправильно.',
    duelTimeout: '⏱️ Час вийшов! За це питання — 0 балів.',
    duelWin: '🏆 <b>Ви перемогли!</b>',
    duelLose: '😔 <b>Ви програли!</b>',
    duelDraw: '🤝 <b>Нічия!</b>',
    myProgress: 'Твій прогрес:\n\n🏅 Досвід (XP): 0\n🔥 Поточний стрік: 0\n\n(Отримуй щоденні бонуси за активність)',
    profile: '👤 Твій профіль буде показано після натискання кнопки «Мій профіль».',
    rewardClaimedSuccess: '🎁 Нагорода нарахована! Дивись результат у повідомленні.',
    rewardAlreadyClaimed: '⏳ Ти вже забрав свою нагороду сьогодні! Повертайся завтра ⏳',
    rewardLocked: '🎁 Кнопка активна раз на 24 години. Спробуй знову завтра.',
    help: 'Довідка по кнопкам:\n\n📚 <b>Пояснити тему</b> - отримай пояснення будь-якої теми\n🧠 <b>Створити тест</b> - AI згенерує тест за темою/матеріалом і дасть пройти його в боті\n⚔️ <b>Дуель знань</b> - випадковий суперник, друг по ID/коду або ШІ (5 питань, 20 с)\n⭐ <b>Premium</b> - фото (Vision) та голосові запити через Gemini\n🎁 <b>Забрати нагороду</b> - отримай щоденний бонус за активність\n📈 <b>Мій прогрес</b> - подивись свій XP та стрік\n📊 <b>Статистика</b> - скільки тем, тестів і повідомлень\n👤 <b>Мій профіль</b> - твої дані та звернення до AI\n📝 <b>Додати КР</b> - заплануй контрольну роботу\n📅 <b>Мої КР</b> - переглянь майбутні контрольні\n⚙️ <b>Допомога</b> - натисни ще раз для деталей',
    helpQuest: '\n🏆 <b>Квести</b> - довгострокові завдання та великі бонуси',
    error: 'Вибачте, сталася помилка. Спробуйте ще раз.',
    punishmentSoft: '💤 Ой! Ти довго не заходив(ла), тому твій вогник активності згас. Стрік скинуто до 0. Повертайся до навчання щодня! 🔥',
    punishmentHard: '😢 О ні! Твій вогник активності згас, і ти втратив(ла) <b>{xp} XP</b> через лінощі. Залишилось XP: <b>{remaining}</b>. Повертайся до навчання! 😢',
    punishmentFreezeUsed: '🧊 Твоя <b>Заморозка стріку</b> спрацювала! Стрік і XP залишились без змін. Наступного разу бережи прогрес сам(а)!',
    progressStatusActive: '🔥 Статус: <b>Вогонь горить</b> — так тримати!',
    progressStatusRisk: '⚠️ Статус: <b>Є ризик втрати прогресу</b> — зайди сьогодні!',
    progressStatusCold: '💤 Статус: <b>Вогонь згас</b> — віднови стрік активності!',
    progressHasFreeze: '🧊 Заморозка стріку: <b>є в інвентарі</b>',
    progressNoFreeze: '🧊 Заморозка стріку: <b>немає</b> (купи за {cost} XP)',
    freezePurchased: '🧊 Ти купив(ла) <b>Заморозку стріку</b> за {cost} XP! Вона один раз захистить тебе від штрафу за пропуск.',
    freezeAlreadyOwned: 'У тебе вже є Заморозка стріку в інвентарі.',
    freezeNotEnoughXp: 'Недостатньо XP. Заморозка коштує {cost} XP.',
    examListTitle: '📅 <b>Мої майбутні контрольні</b>',
    examListEmpty: '📅 У тебе поки немає запланованих КР.\n\nНатисни «📝 Додати КР» або /add_exam',
    examListHint: 'Натисни кнопку, щоб редагувати назву, дату або видалити КР.',
    examAskDate: '📅 Введи дату та час КР у форматі <b>ДД.ММ.РРРР ЧЧ:ММ</b>\n\nПриклад: <code>25.07.2026 10:00</code>\n🌍 Часовий пояс: <b>{timezone}</b>',
    examDateInvalid: '❌ Невірний формат. Введи дату так: <b>ДД.ММ.РРРР ЧЧ:ММ</b>\nПриклад: 25.07.2026 10:00',
    examDatePast: '❌ Ця дата вже минула. Обери майбутню дату.',
    examTitleTooShort: 'Назва занадто коротка. Введи мінімум 2 символи.',
    examCreated: '✅ КР <b>«{title}»</b> додано!\n📅 Дата: <b>{date}</b>\n\nЯ нагадаю за 2 дні, за 1 день і за 2 години до КР.',
    examUpdated: '✅ Назву КР оновлено: <b>{title}</b>',
    examDateUpdated: '✅ Дату КР оновлено: <b>{date}</b>',
    examDeleted: '🗑 КР видалено.',
    examDeletedShort: 'Видалено',
    examDeleteConfirm: '🗑 Видалити КР <b>«{title}»</b>?',
    examEditTitle: '✏️ Введи нову назву для КР <b>«{title}»</b>:',
    examNotFound: 'КР не знайдено.',
    examReminder2d: '⏰ <b>Нагадування:</b> через 2 дні у тебе контрольна з теми «<b>{title}</b>».\n📅 {date}\n\nЧас почати готуватися!',
    examReminder1d: '⏰ <b>Нагадування:</b> завтра у тебе контрольна з теми «<b>{title}</b>».\n📅 {date}\n\nЧас повторити матеріал!',
    examReminder2h: '🍀 Контрольна з теми «<b>{title}</b>» вже за 2 години!\n📅 {date}\n\nУдачі!',
  },
};
