// Configuration for Schoolmate-Ai Bot
module.exports = {
  // Replace with your Telegram Bot Token from BotFather
  TELEGRAM_TOKEN: process.env.TELEGRAM_TOKEN || 'YOUR_BOT_TOKEN_HERE',

  punishment: {
    softThresholdHours: 24,
    hardThresholdDays: 3,
    xpPenalty: 50,
    freezeItemCost: 100,
    riskThresholdHours: 18,
    checkIntervalHours: 6,
  },

  exams: {
    defaultTimezone: 'Europe/Kyiv',
    checkIntervalMinutes: 1,
    reminderWindowMinutes: 10,
    reminders: [
      { field: 'notified2d', offsetMs: 2 * 24 * 60 * 60 * 1000, messageKey: 'examReminder2d' },
      { field: 'notified1d', offsetMs: 24 * 60 * 60 * 1000, messageKey: 'examReminder1d' },
      { field: 'notified2h', offsetMs: 2 * 60 * 60 * 1000, messageKey: 'examReminder2h' },
    ],
  },

  // Bot messages
  messages: {
    start: 'Привіт 👋 Ласкаво просимо до Schoolmate AI!\n\nЯ допоможу тобі з навчанням. Вибери, що тебе цікавить:',
    explainTopic: 'Яку тему ти хочеш розібрати? Напиши назву теми або номер параграфа.',
    createTest: '🧠 <b>Створення тесту</b>\n\n<i>Ця функція з\'явиться пізніше від AI.</i>',
    myProgress: 'Твій прогрес:\n\n🏅 Досвід (XP): 0\n🔥 Поточний стрік: 0\n\n(Отримуй щоденні бонуси за активність)',
    profile: '👤 Твій профіль буде показано після натискання кнопки «Мій профіль».',
    rewardClaimedSuccess: '🎁 Нагорода нарахована! Дивись результат у повідомленні.',
    rewardAlreadyClaimed: '⏳ Ти вже забрав свою нагороду сьогодні! Повертайся завтра ⏳',
    rewardLocked: '🎁 Кнопка активна раз на 24 години. Спробуй знову завтра.',
    help: 'Довідка по кнопкам:\n\n📚 <b>Пояснити тему</b> - отримай пояснення будь-якої теми\n🧠 <b>Створити тест</b> - генеруй тести для тренування (скоро від AI)\n🎁 <b>Забрати нагороду</b> - отримай щоденний бонус за активність\n📈 <b>Мій прогрес</b> - подивись свій XP та стрік\n📊 <b>Статистика</b> - скільки тем, тестів і повідомлень\n👤 <b>Мій профіль</b> - твої дані та звернення до AI\n📝 <b>Додати КР</b> - заплануй контрольну роботу\n📅 <b>Мої КР</b> - переглянь майбутні контрольні\n⚙️ <b>Допомога</b> - натисни ще раз для деталей',
    helpQuest: '\n🏆 <b>Квести</b> - довгострокові завдання та великі бонуси',
    error: 'Вибачте, сталася помилка. Спробуйте ще раз.',
    punishmentSoft: '💤 Ой! Ти довго не заходив(ла), тому твій вогник активності згас. Стрік скинуто до 0. Повертайся до навчання щодня! 🔥',
    punishmentHard: '😢 О ні! Твій вогник активності згас, і ти втратив(ла) <b>{xp} XP</b> через лінощі. Залишилось XP: <b>{remaining}</b>. Повертайся до навчання! 😢',
    punishmentFreezeUsed: '🧊 Твоя <b>Заморозка стріку</b> спрацювала! Стрік і XP залишились без змін. Наступного разу бережи прогрес сам(а)!',
    progressStatusActive: '🔥 Статус: <b>Вогонь горить</b> — так тримати!',
    progressStatusRisk: '⚠️ Статус: <b>Є ризик втрати прогресу</b> — зайди сьогодні!',
    progressStatusCold: '💤 Статус: <b>Вогонь згас</b> — віднови стрік активності!',
    progressHasFreeze: '🧊 Заморозка стріку: <b>є в інвентарі</b>',
    progressNoFreeze: '🧊 Заморозка стріку: <b>немає</b> (купи за {cost} XP)',
    freezePurchased: '🧊 Ти купив(ла) <b>Заморозку стріку</b> за {cost} XP! Вона один раз захистить тебе від штрафу за пропуск.',
    freezeAlreadyOwned: 'У тебе вже є Заморозка стріку в інвентарі.',
    freezeNotEnoughXp: 'Недостатньо XP. Заморозка коштує {cost} XP.',
    examListTitle: '📅 <b>Мої майбутні контрольні</b>',
    examListEmpty: '📅 У тебе поки немає запланованих КР.\n\nНатисни «📝 Додати КР» або /add_exam',
    examListHint: 'Натисни кнопку, щоб редагувати назву, дату або видалити КР.',
    examAskDate: '📅 Введи дату та час КР у форматі <b>ДД.ММ.РРРР ЧЧ:ММ</b>\n\nПриклад: <code>25.07.2026 10:00</code>\n🌍 Часовий пояс: <b>{timezone}</b>',
    examDateInvalid: '❌ Невірний формат. Введи дату так: <b>ДД.ММ.РРРР ЧЧ:ММ</b>\nПриклад: 25.07.2026 10:00',
    examDatePast: '❌ Ця дата вже минула. Обери майбутню дату.',
    examTitleTooShort: 'Назва занадто коротка. Введи мінімум 2 символи.',
    examCreated: '✅ КР <b>«{title}»</b> додано!\n📅 Дата: <b>{date}</b>\n\nЯ нагадаю за 2 дні, за 1 день і за 2 години до КР.',
    examUpdated: '✅ Назву КР оновлено: <b>{title}</b>',
    examDateUpdated: '✅ Дату КР оновлено: <b>{date}</b>',
    examDeleted: '🗑 КР видалено.',
    examDeletedShort: 'Видалено',
    examDeleteConfirm: '🗑 Видалити КР <b>«{title}»</b>?',
    examEditTitle: '✏️ Введи нову назву для КР <b>«{title}»</b>:',
    examNotFound: 'КР не знайдено.',
    examReminder2d: '⏰ <b>Нагадування:</b> через 2 дні у тебе контрольна з теми «<b>{title}</b>».\n📅 {date}\n\nЧас почати готуватися!',
    examReminder1d: '⏰ <b>Нагадування:</b> завтра у тебе контрольна з теми «<b>{title}</b>».\n📅 {date}\n\nЧас повторити матеріал!',
    examReminder2h: '🍀 Контрольна з теми «<b>{title}</b>» вже за 2 години!\n📅 {date}\n\nУдачі!',
  },
};
